schema_version = "1.0.0"

id = "palettax"
version = "1.1.2"
name = "Palettax"
tagline = "Upgrade color palette management in Blender"
maintainer = "Carlos Sala Samper"
type = "add-on"
website = "https://godofprogramming.com"
icon = "icon.png"

tags = ["Import-Export", "Paint"]

blender_version_min = "5.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import a palette file selected by the user"
